/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/add-company": {
    post: {
      responses: {
        /** Company added */
        200: unknown;
      };
      /** add company */
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            siteUrl?: string;
            logoUrl?: string;
            /** Format: date */
            createDate?: string;
          };
        };
      };
    };
  };
}

export interface components {}

export interface operations {}

export interface external {}
