export { default as authSchema } from './auth-schema.js'
export { default as addNewSingerSchema } from './add-new-singer-schema.js'
export { default as getSingerSchema } from './get-singer-schema.js'
export { default as singerUpdateSchema } from './update-singer-schema.js'
export { default as addLinkSchema } from './add-new-link-schema.js'
export { default as getLinkSchema } from './get-link-schema.js'
export { default as updateLinkSchema } from './update-link-schema.js'